error: 
    status - 500 
    message - Error: Cast to undefined failed for value undefined at path "undefined"
    at CastError.<anonymous> (C:\Users\soora\Desktop\test\awesome-project\node_modules\core-js\internals\wrap-error-constructor-with-cause.js:37:62)
    at new Error (C:\Users\soora\Desktop\test\awesome-project\node_modules\core-js\modules\es.error.cause.js:28:43)
    at new MongooseError (C:\Users\soora\Desktop\test\awesome-project\node_modules\mongoose\lib\error\mongooseError.js:7:1)
    at new CastError (C:\Users\soora\Desktop\test\awesome-project\node_modules\mongoose\lib\error\cast.js:31:7)
    at model.Query.exec (C:\Users\soora\Desktop\test\awesome-project\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\soora\Desktop\test\awesome-project\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) 
    url - /api/v1/users/newuser 
    method - PUT 
    IP - ::ffff:127.0.0.1
   {"timestamp":"2022-06-24T03:10:28.427Z"}
error: 
    status - 500 
    message - Error: student validation failed
    at ValidationError.<anonymous> (C:\Users\soora\Desktop\test\awesome-project\node_modules\core-js\internals\wrap-error-constructor-with-cause.js:37:62)
    at new Error (C:\Users\soora\Desktop\test\awesome-project\node_modules\core-js\modules\es.error.cause.js:28:43)
    at new MongooseError (C:\Users\soora\Desktop\test\awesome-project\node_modules\mongoose\lib\error\mongooseError.js:7:1)
    at new ValidationError (C:\Users\soora\Desktop\test\awesome-project\node_modules\mongoose\lib\error\validation.js:27:5)
    at model.Document.invalidate (C:\Users\soora\Desktop\test\awesome-project\node_modules\mongoose\lib\document.js:2782:32)
    at model.$set (C:\Users\soora\Desktop\test\awesome-project\node_modules\mongoose\lib\document.js:1349:12)
    at model.$set (C:\Users\soora\Desktop\test\awesome-project\node_modules\mongoose\lib\document.js:1058:16)
    at model.Document (C:\Users\soora\Desktop\test\awesome-project\node_modules\mongoose\lib\document.js:148:12)
    at model.Model (C:\Users\soora\Desktop\test\awesome-project\node_modules\mongoose\lib\model.js:106:12)
    at new model (C:\Users\soora\Desktop\test\awesome-project\node_modules\mongoose\lib\model.js:4911:15)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\mongoose\lib\model.js:3157:22
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\mongoose\lib\model.js:3193:7
    at Array.forEach (<anonymous>)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\mongoose\lib\model.js:3192:15
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>) 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-16T07:19:26.668Z"}
error: 
    status - 500 
    message - Error: Malformed part header
    at Error.<anonymous> (C:\Users\soora\Desktop\test\awesome-project\node_modules\core-js\internals\wrap-error-constructor-with-cause.js:37:62)
    at new Error (C:\Users\soora\Desktop\test\awesome-project\node_modules\core-js\modules\es.error.cause.js:28:43)
    at SBMH.ssCb [as _cb] (C:\Users\soora\Desktop\test\awesome-project\node_modules\busboy\lib\types\multipart.js:398:32)
    at feed (C:\Users\soora\Desktop\test\awesome-project\node_modules\streamsearch\lib\sbmh.js:219:14)
    at SBMH.push (C:\Users\soora\Desktop\test\awesome-project\node_modules\streamsearch\lib\sbmh.js:104:16)
    at Multipart._write (C:\Users\soora\Desktop\test\awesome-project\node_modules\busboy\lib\types\multipart.js:567:19)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Multipart.Writable.write (internal/streams/writable.js:303:10)
    at IncomingMessage.ondata (internal/streams/readable.js:719:22)
    at IncomingMessage.emit (events.js:315:20)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at IncomingMessage.Readable.read (internal/streams/readable.js:519:10)
    at flow (internal/streams/readable.js:992:34)
    at resume_ (internal/streams/readable.js:973:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-16T08:17:36.772Z"}
error: 
    status - 500 
    message - Error: Malformed part header
    at Error.<anonymous> (C:\Users\soora\Desktop\test\awesome-project\node_modules\core-js\internals\wrap-error-constructor-with-cause.js:37:62)
    at new Error (C:\Users\soora\Desktop\test\awesome-project\node_modules\core-js\modules\es.error.cause.js:28:43)
    at SBMH.ssCb [as _cb] (C:\Users\soora\Desktop\test\awesome-project\node_modules\busboy\lib\types\multipart.js:398:32)
    at feed (C:\Users\soora\Desktop\test\awesome-project\node_modules\streamsearch\lib\sbmh.js:219:14)
    at SBMH.push (C:\Users\soora\Desktop\test\awesome-project\node_modules\streamsearch\lib\sbmh.js:104:16)
    at Multipart._write (C:\Users\soora\Desktop\test\awesome-project\node_modules\busboy\lib\types\multipart.js:567:19)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Multipart.Writable.write (internal/streams/writable.js:303:10)
    at IncomingMessage.ondata (internal/streams/readable.js:719:22)
    at IncomingMessage.emit (events.js:315:20)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at IncomingMessage.Readable.read (internal/streams/readable.js:519:10)
    at flow (internal/streams/readable.js:992:34)
    at resume_ (internal/streams/readable.js:973:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-16T08:23:24.166Z"}
error: 
    status - 500 
    message - Error: Malformed part header
    at Error.<anonymous> (C:\Users\soora\Desktop\test\awesome-project\node_modules\core-js\internals\wrap-error-constructor-with-cause.js:37:62)
    at new Error (C:\Users\soora\Desktop\test\awesome-project\node_modules\core-js\modules\es.error.cause.js:28:43)
    at SBMH.ssCb [as _cb] (C:\Users\soora\Desktop\test\awesome-project\node_modules\busboy\lib\types\multipart.js:398:32)
    at feed (C:\Users\soora\Desktop\test\awesome-project\node_modules\streamsearch\lib\sbmh.js:219:14)
    at SBMH.push (C:\Users\soora\Desktop\test\awesome-project\node_modules\streamsearch\lib\sbmh.js:104:16)
    at Multipart._write (C:\Users\soora\Desktop\test\awesome-project\node_modules\busboy\lib\types\multipart.js:567:19)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Multipart.Writable.write (internal/streams/writable.js:303:10)
    at IncomingMessage.ondata (internal/streams/readable.js:719:22)
    at IncomingMessage.emit (events.js:315:20)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at IncomingMessage.Readable.read (internal/streams/readable.js:519:10)
    at flow (internal/streams/readable.js:992:34)
    at resume_ (internal/streams/readable.js:973:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-16T10:03:07.836Z"}
error: 
    status - 500 
    message - Error: ENOENT: no such file or directory, open 'C:\Users\soora\Desktop\test\awesome-project\uplode\imagePath-1663322744180.jpg' 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-16T10:05:44.202Z"}
error: 
    status - 500 
    message - Error: ENOENT: no such file or directory, open 'C:\Users\soora\Desktop\test\awesome-project\uplode\imagePath1663323285702.jpg' 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-16T10:14:45.706Z"}
error: 
    status - 500 
    message - Error: ENOENT: no such file or directory, open 'C:\Users\soora\Desktop\test\awesome-project\uplode\imagePath1663323302253.jpg' 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-16T10:15:02.257Z"}
error: 
    status - 500 
    message - Error: ENOENT: no such file or directory, open 'C:\uplode\imagePath1663323330008.jpg' 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-16T10:15:30.012Z"}
error: 
    status - 500 
    message - Error: ENOENT: no such file or directory, open 'C:\Users\soora\Desktop\test\awesome-project\uplode\ignoring online 2.jpg' 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-19T10:03:23.638Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'path' of undefined
    at _callee$ (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:14:26)
    at tryCatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at newUser (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:5:21)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at multerMiddleware (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:13:41)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:114:3) 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-22T14:38:57.594Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'filename' of undefined
    at _callee$ (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:14:68)
    at tryCatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at newUser (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:5:21)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at multerMiddleware (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:13:41)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:114:3) 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-22T15:24:27.282Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'filename' of undefined
    at _callee$ (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:14:68)
    at tryCatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at newUser (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:5:21)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at multerMiddleware (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:13:41)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:114:3) 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-22T16:04:56.027Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'path' of undefined
    at _callee$ (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:14:68)
    at tryCatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at newUser (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:5:21)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at multerMiddleware (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:13:41)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:114:3) 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-22T16:05:58.143Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'path' of undefined
    at _callee$ (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:14:68)
    at tryCatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at newUser (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:5:21)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at multerMiddleware (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:13:41)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:114:3) 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-23T03:19:11.995Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'filename' of undefined
    at _callee$ (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:14:68)
    at tryCatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at newUser (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:5:21)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at multerMiddleware (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:13:41)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:114:3) 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-23T10:21:33.429Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'filename' of undefined
    at _callee$ (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:14:68)
    at tryCatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at newUser (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:5:21)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at done (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:45:7)
    at indicateDone (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:49:68)
    at Multipart.<anonymous> (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:166:7)
    at Multipart.emit (events.js:315:20) 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-24T05:23:45.619Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'filename' of undefined
    at _callee$ (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:14:68)
    at tryCatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at newUser (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:5:21)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at done (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:45:7)
    at indicateDone (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:49:68)
    at Multipart.<anonymous> (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:166:7)
    at Multipart.emit (events.js:315:20) 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-24T05:30:39.047Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'path' of undefined
    at _callee$ (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:18:68)
    at tryCatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at newUser (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:9:21)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at done (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:45:7)
    at indicateDone (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:49:68)
    at Multipart.<anonymous> (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:166:7)
    at Multipart.emit (events.js:315:20) 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-24T05:33:50.022Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'path' of undefined
    at _callee$ (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:18:68)
    at tryCatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at newUser (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:9:21)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at done (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:45:7)
    at indicateDone (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:49:68)
    at Multipart.<anonymous> (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:166:7)
    at Multipart.emit (events.js:315:20) 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-24T05:58:03.603Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'path' of undefined
    at _callee$ (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:18:68)
    at tryCatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at newUser (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:9:21)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at done (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:45:7)
    at indicateDone (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:49:68)
    at Multipart.<anonymous> (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:166:7)
    at Multipart.emit (events.js:315:20) 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-24T06:17:42.297Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'originalname' of undefined
    at _callee$ (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:18:68)
    at tryCatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at newUser (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:9:21)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at done (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:45:7)
    at indicateDone (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:49:68)
    at Multipart.<anonymous> (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:166:7)
    at Multipart.emit (events.js:315:20) 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-24T06:19:42.921Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'ACCEPTED' of undefined
    at _callee$ (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:18:68)
    at tryCatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at newUser (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:9:21)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at done (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:45:7)
    at indicateDone (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:49:68)
    at Multipart.<anonymous> (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:166:7)
    at Multipart.emit (events.js:315:20) 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-24T06:24:10.555Z"}
error: 
    status - 500 
    message - TypeError: Cannot read property 'path' of undefined
    at _callee$ (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:18:68)
    at tryCatch (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\soora\Desktop\test\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at newUser (C:\Users\soora\Desktop\test\awesome-project\src\controllers\/user.controller.js:9:21)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\test\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at done (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:45:7)
    at indicateDone (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:49:68)
    at Multipart.<anonymous> (C:\Users\soora\Desktop\test\awesome-project\node_modules\multer\lib\make-middleware.js:166:7)
    at Multipart.emit (events.js:315:20) 
    url - /api/v1/users/student 
    method - POST 
    IP - ::1
   {"timestamp":"2022-09-24T09:37:07.589Z"}
error: 
    status - 500 
    message - Error: "dob" must be a valid email 
    url - /api/v1/people 
    method - POST 
    IP - ::1
   {"timestamp":"2022-10-05T17:46:52.168Z"}
error: 
    status - 500 
    message - ReferenceError: UserService is not defined
    at _callee$ (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\src\controllers\/assi.controller.js:3:24)
    at tryCatch (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at newUser (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\src\controllers\/assi.controller.js:3:21)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at newPeopleValidator (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\src\validators\/assin.validator.js:16:5)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\express\lib\router\route.js:114:3) 
    url - /api/v1/people 
    method - POST 
    IP - ::1
   {"timestamp":"2022-10-05T17:47:44.189Z"}
error: 
    status - 500 
    message - ReferenceError: UserService is not defined
    at _callee3$ (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\src\controllers\/assi.controller.js:30:31)
    at tryCatch (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at updatePeople (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\src\controllers\/assi.controller.js:30:28)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\express\lib\router\index.js:284:15
    at param (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\express\lib\router\index.js:365:14) 
    url - /api/v1/people/633dcd3f2f2d602438cdaab5 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-10-05T18:42:34.959Z"}
error: 
    status - 500 
    message - Error: Cast to undefined failed for value undefined at path "undefined"
    at CastError.<anonymous> (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\core-js\internals\wrap-error-constructor-with-cause.js:37:62)
    at new Error (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\core-js\modules\es.error.cause.js:28:43)
    at new MongooseError (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\mongoose\lib\error\mongooseError.js:7:1)
    at new CastError (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\mongoose\lib\error\cast.js:31:7)
    at model.Query.exec (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\soora\Desktop\Basic_project_nodejs\awesome-project\node_modules\mongoose\lib\query.js:4592:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) 
    url - /api/v1/people/undefined 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-10-06T03:27:00.936Z"}
